---
title: "Coucou et bienvenue!"
---

:::::::::: animated-text
Rendre tes données

::::::::: flip
<div>

<div>

accesibles

</div>

</div>

<div>

<div>

claires

</div>

</div>

<div>

<div>

plus fun

</div>

</div>
:::::::::

pour booster tes projets!
::::::::::

::::::::::::::::: grid
::: g-col-12
Je suis ravie que tu sois ici ! 🌸

Bienvenue sur mon site personnel — un espace où je partage mon amour pour les données, la créativité et, bien sûr, l’enseignement.

Ici, tu trouveras du contenu sur R, Python, la science des données et d’autres choses que j’explore.

Si tu es curieux·se de savoir comment je peux t’aider, voici mes services :
:::

:::::: {.g-col-12 .g-col-md-4}
::::: {.card .text-white .bg-secondary}
::: card-header
📊 Analyse de données
:::

::: card-body
<p class="card-text">

Valorisons vos données avec statistiques, graphiques et idées claires — toujours avec des résultats reproductibles et automatisés.

</p>
:::
:::::
::::::

:::::: {.g-col-12 .g-col-md-4}
::::: {.card .text-white .bg-info}
::: card-header
🎓 Formations
:::

::: card-body
<p class="card-text">

Ateliers et formations en R, Python ou gestion de données — pour optimiser vos analyses et développer vos compétences en toute confiance.

</p>
:::
:::::
::::::

:::::: {.g-col-12 .g-col-md-4}
::::: {.card .text-white .bg-success}
::: card-header
💡 Blog et conseils
:::

::: card-body
<p class="card-text">

Sur mon blog, je partage ressources, tutos et réflexions — des astuces de code aux idées qui m’inspirent.

</p>
:::
:::::
::::::

::: g-col-12
N’hésite pas à explorer mon site et à me contacter, je serai ravie d’échanger avec toi. – À bientôt !

*"Rendre les données complexes simples, utiles et fiables pour tous."*
:::
:::::::::::::::::

```{=html}
<!-- Calendly badge widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/anapaodares/30min?primary_color=26c595', text: '📅 Parlons-en!', color: '#15d3a6', textColor: '#ffffff', branding: false }); }</script>
<!-- Calendly badge widget end -->
```
